# File location: vidya/ci/github_actions.yml

name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        # Placeholder command for running the testing suite
        python vidya/tests/run_all_tests.py
        
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
        
  build_docker_image:
    runs-on: ubuntu-latest
    needs: build_and_test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: your-docker-hub-username/vidya-ai:latest
